---
title: "UNESCO_WDPA"
author: "Nick McManus"
date: "7/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)  # polygons
library(raster) #raster package
library(terra)  # newer/faster/better raster package
library(rnaturalearth)  #administrative boundaries data
library(exactextractr)  # extracting what's underneath polys, points
library(kableExtra)
library(tidyverse)
```

## Read in Data

As the country with the second highest number of UNESCO world heritage sites, we'll examine China

```{r}
# get china from rnaturalearth data
china <- ne_countries(
  scale = "medium",
  country = "China",
  returnclass = "sf") %>% 
  dplyr::select(sovereignt)

# plot
ggplot() +
  geom_sf(data = china)
```

```{r}
# define crs so it's the same across everything
my_crs <- st_crs(china)
```


## WDPA protected areas
UNEP-WCMC and IUCN (2021), Protected Planet: The World Database on Protected Areas (WDPA) [On-line], Cambridge, UK: UNEP-WCMC and IUCN. Available at: www.protectedplanet.net
```{r}
# read in raster with terra::rast
wdpa_global <- rast("data/wdpa_raster.tif") 

# transform china to crop bc it's faster than re projecting the whole global raster
china_trans <- china %>% 
  st_transform(crs = crs(wdpa_global)) %>% 
  vect() # vect is more agreeable to rasts

# crop and mask chen to china then project back to our crs
wdpa <- wdpa_global %>% 
  crop(china_trans) %>% 
  mask(china_trans) %>% 
  terra::project(y = crs(china))

plot(wdpa)
```
 

## UNESCO Cultual Sites

```{r}
unesco <- read_csv("data/whc-cultural-sites-2021.csv") %>% 
  st_as_sf(coords = c("longitude", "latitude"),
           crs = st_crs("epsg:4326")) %>% 
  filter(states_name_en == "China") %>%
  st_transform(crs = my_crs) %>% 
  dplyr::select(name_en) %>% 
  mutate(ID = row_number()) # define id for joining later

ggplot() + 
  geom_sf(data = china) + 
  geom_sf(data = unesco, 
          color = "blue") 
```



## Define overlaps
### UNESCO + WDPA
```{r}
# vects play better with rasts (both are terra)
unesco_vect <- vect(unesco)

plot(wdpa)
plot(unesco_vect, col = "blue", add = TRUE)
```

```{r}
# use extract to extract what's underneath points
wdpa_overlap <- terra::extract(
  x = wdpa,
  y = unesco_vect) %>% 
  rename(wdpa_overlap = 2) %>% 
  mutate(wdpa_overlap = as.logical(wdpa_overlap)) %>% # change to true/false 
  right_join(unesco, by = "ID") %>%  # join back with unesco data
  dplyr::select(!c(geometry, ID)) %>% # clean df
  relocate(name_en, .before = wdpa_overlap)

kable(wdpa_overlap) %>% 
  kable_styling(bootstrap_options = "striped") %>% 
  scroll_box(height = "400px")
```

